### PR TITLE
Prevent users to fill out confirmation form without being admitted

### PR DESCRIPTION
**Pull request by xTEddie**
Users are able to go the confirmation page through the URL. This PR should fix the issue.

### CODE REVIEW

**Comment by jlin816** [comment]
Thanks @xTEddie !

**Comment by chriswongtv** [comment]
Correct me if I'm wrong but isn't `completedProfile` within the `status` property of the `User` object that gets set to `true` when the application is completed (not admitted)? I made a similar fix for HackUCI that uses the `User.status.admitted` property instead: https://github.com/hackuci/quill/pull/63/files.

**Comment by xTEddie** [comment]
@chriswongtv you’re right. Your fix works too!

**Comment by chriswongtv** [comment]
@xTEddie I've just tested it locally and `Session.getUser().completedProfile` is always `undefined` because the `completedProfile` property does not exist. As a result, `!Session.getUser().completedProfile` resolves to true and it will always redirect users who's trying to get to the confirmation page to the dashboard (regardless if they are admitted). I tried changing `Session.getUser().completedProfile` to `Session.getUser().status.completedProfile` where the property exists, but now anyone who has submitted an application (instead of admitted) has the ability to see the confirmation page and submit the form. Therefore I believe we should be checking the `Session.getUser().status.admitted` property instead.

**Comment by xTEddie** [comment]
I retested it and you're right. It should be `Session.getUser().status.completedProfile`  instead. Looking at the **completedProfile** status is not enough. Your fix would make more sense. Thanks for pointing this out. You can make a PR on that repo to fix it. Thanks!

**Comment by chriswongtv** [comment]
@xTEddie Opened #45. Glad we sorted this out!

**Comment by jlin816** [comment]
Oh man, my bad for missing this -- thanks for pointing it out, @chriswongtv 👍

**Pull request merged**
